name: perseus_vr_lab_app
description: "Warnell VR Lab App for the PERSEUS Project"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^8.2.1
  url_launcher: ^6.3.1
  visibility_detector: ^0.4.0


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_launcher_icons: "^0.14.4"

flutter:
  uses-material-design: true
  assets:
    - lib/assets/images/
    - lib/assets/WarnellVRLabAppIcon.png

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "lib/assets/WarnellVRLabAppIcon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "lib/assets/WarnellVRLabAppIcon.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"
  windows:
    generate: true
    image_path: "lib/assets/WarnellVRLabAppIcon.png"
    icon_size: 48 # min:48, max:256, default: 48
  macos:
    generate: true
    image_path: "lib/assets/WarnellVRLabAppIcon.png"